# Data Visualization with OpenCPU
##### Columbia University - STAT 5702
##### 2019 EDAV Community Contribution

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introducion

### What is OpenCPU?
[OpenCPU](https://www.opencpu.org/) is a "API for Embedded Scientific Computing." OpenCPU consits of 3 main parts:

- a server to host OpenCPU apps locally or on the cloud,
- a HTTP API for data analysis using R, and
- a JavaScript library to integrate everything together. 

OpenCPU works as a platform to create web apps centered around using R for any needed data analysis and visualizations. 

### What is this Tutorial? 
There is not a whole lot of information out there having to do with actually creating an OpenCPU app, so this tutorial will attempt to piece what information is available together by working through an example project. There are 4 major steps involved:

- [Creating a Disfunctional App](#creating-a-disfunctional-app): creating an R package to acomplish the data processing we need and the HTML for the user to interact with, 
- connecting the HTML to the R package with the OpenCPU JavaScript library, 
- testing the app locally, and
- deploying the app to the OpenCPU Cloud. 

> As a note, when you see text in brackets around text, that is intended to be completly replaced. For example: [package_name] _becomes_ distogram.

As mentioned, this tutorial will be centered around an example... enter Distogram. 

### Distogram: A Working OpenCPU Example
I wanted to keep things relatively simple, but I think this example gets the point across of the power of using R in the browser. Distogram is an app that prompts users to choose a sample size and probability distribution to sample from, uses R to create a histogram based on these and other parameters, and then presents that plot in the browser. Later I will go through the steps of sourcing this app locally if you chose to do that, but for now, if you want an idea of where this will work towards, please visit https://mbmackenzie.ocpu.io/distogram to view this project.

## Creating a Disfunctional App
The first step in creating an OpenCPU app is to fist create an app that does not work. What I mean by this is to build all the R, HTML, CSS, and some JavaScript. While I will not go through all the bits of this since the main point is OpenCPU, all the code is on github [here](https://github.com/mbmackenzie/distogram).

### Standalone Package
OpenCPU apps require a build-able R package specific to the app. For completeness on building a package in R, I'd point you to this resource: [R packages](http://r-pkgs.had.co.nz/). However, I will go through what seems to be the minimum for OpenCPU.

#### DESCRIPTION
The DESCRIPTION file stores important metadata about the package such as name, author, description, version, etc... Below is a template for creating a DESCRIPTION file.

```
Package: [package_name]
Type: Package
Title: [title]
Version: [x.x.x]
Date: [YYYY-MM-DD]
Author: [author_name]
Maintainer: [maintainer_name] <[maintainer_email]>
Description: [Description]
License: MIT
RoxygenNote: 6.1.1
```

#### /R
The `/R` directory is responsible for holding the necessary code. 
















